name: Build Plugins

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Clone
        uses: actions/checkout@v2

      - name: Build Plugins
        run: dotnet publish -c Release src/Artemis.Plugins.Games.Subnautica.Module/Artemis.Plugins.Games.Subnautica.Module.csproj

      - name: Upload ArtemisSubnautica Module
        uses: actions/upload-artifact@v3
        with:
          name: Artemis.Plugins.Games.Subnautica.Module
          path: src/Artemis.Plugins.Games.Subnautica.Module/bin/Release/net6.0/publish
          if-no-files-found: error

      - name: Upload Artemis Stardew Valley GSI
        uses: actions/upload-artifact@v3
        with:
          name: Artemis.Plugins.Games.Subnautica.GSI
          path: src/Artemis.Plugins.Games.Subnautica.GSI/artifactory/Artemis.Plugins.Games.Subnautica.GSI.zip
          if-no-files-found: error
